name: saman_vertex_interview
channels:
  - conda-forge
dependencies:
  - python=3.10.16
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.15.2
  - scikit-learn=1.6.1
  - statsmodels=0.14.4
  - imbalanced-learn=0.12.4
  - xgboost=2.1.4
  - matplotlib=3.10.1
  - seaborn=0.13.2
  - joblib=1.4.2
  - threadpoolctl=3.5.0
  - ipykernel=6.29.5
  - ipython=8.33.0
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - pip=25.0.1
  - tqdm=4.67.1
  - pip:
      - sklearn-compat==0.1.3
